# **Bibliotecas**

In [2]:
%pip install pandas==2.3.3

Requirement already satisfied: pandas==2.3.3 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.3.3) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from pandas==2.3.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.3.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.3.3) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas==2.3.3) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns, plotly.express as px

In [4]:
print (pd.__version__)

2.3.3

In [5]:
ventas = pd.read_csv ('ventas.csv', sep= '#')
ventas.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

# **Transformación del df ventas**

In [6]:
ventas = ventas [['fecha_pedido', 'modo_envio', 'nombre_cliente', 'segmento_cliente', 'ciudad', 'provincia', 'region', 'departamento', 'tipo_producto', 'ventas', 'cantidad', 'ganancia']]
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,49.72,2,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,3255.75,5,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,76.04,2,4.28

## *Formato de fecha*

In [7]:
ventas['fecha_pedido'] = pd.to_datetime (ventas['fecha_pedido'], format= '%Y-%m-%d')
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.2+ KB

In [8]:
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,49.72,2,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,3255.75,5,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,76.04,2,4.28

## *Principales clientes*

In [9]:
clientes = ventas.groupby (['nombre_cliente'])['ventas'].sum().nlargest (10).copy()
clientes = clientes.reset_index()
clientes.head()

    nombre_cliente    ventas
0  Víctor Carrasco  73370.61
1      Brisa Rojas  68868.11
2     Mateo Vargas  62749.75
3    Vicente Rojas  59544.11
4      Laura Rojas  51398.87

In [10]:
clientes = clientes.rename (columns= {'nombre_cliente': 'Clientes', 'ventas': 'Ventas'}) #Más sencillo con clientes.columns = ['Clientes', 'Ventas']
clientes.head(3)

          Clientes    Ventas
0  Víctor Carrasco  73370.61
1      Brisa Rojas  68868.11
2     Mateo Vargas  62749.75

In [11]:
clientes['Ranking'] = clientes.index + 1
clientes.set_index ('Ranking', inplace= True)
clientes.head()

                Clientes    Ventas
Ranking
1        Víctor Carrasco  73370.61
2            Brisa Rojas  68868.11
3           Mateo Vargas  62749.75
4          Vicente Rojas  59544.11
5            Laura Rojas  51398.87

## *Estilizando tablas (Style)*

In [12]:
estilo = clientes.style
estilo

### *Cambiar formato a las ventas*

In [13]:
estilo.format ({'Ventas': '{:,.2f}'})
estilo

### *Ejercicio tienda de libros*

Tenemos un informe de costos de venta de libros y películas de una tienda. Durante los desafíos, la misión será trabajar con los datos para crear tablas que se adapten a las necesidades de diversos análisis que pueden realizarse en la tienda. Para una mejor comprensión de los datos, a continuación se muestra lo que representa cada dato en las columnas.

- pais: país de destino del producto.
- id_cliente: código de identificación del cliente solicitante.
- fecha_pedido: fecha de solicitud del producto por parte del cliente.
- fecha_llegada: fecha de llegada del producto a la dirección de entrega proporcionada por el cliente.
- tipo_compra: categoría a la que pertenece la compra, que puede ser Normal o Devolución.
- numero_pedido: código de identificación de la compra realizada.
- tamano_pacote: tamaño del paquete para el envío del pedido.
- unidades: cantidad de unidades compradas en el pedido.
- costo_empacado: valor del costo de empaquetado del producto para la tienda.
- costo_envio: valor del costo de envío del producto para la tienda.
- tipo_descuento: categoría del tipo de descuento aplicado.
- categoria: categoría del tipo de producto.
- tipo_consumo: nivel de consumo del producto por tiempo de uso.
- tipo_cliente: categoría del tipo de cliente.
- costo_producto: valor total del costo que resulta el pedido para la tienda.

***El primer desafío es construir una visualización que permita identificar qué países han solicitado más productos por pedidos, para así poder realizar un estudio sobre la distribución y logística de productos.***

In [14]:
libros = pd.read_csv ('tienda_libros.csv', sep= ',')
display (libros.head())
print (libros.shape)

,pais,id_cliente,fecha_pedido,fecha_llegada,tipo_compra,numero_pedido,tamano_paquete,unidades,costo_empacado,costo_envio,tipo_descuento,categoria,tipo_consumo,tipo_cliente,costo_producto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Paquete pequeño,1,3.0,5.99,Sin descuento,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Paquete pequeño,3,1.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Paquete pequeño,1,3.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolución,98077986,Paquete pequeño,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Paquete pequeño,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

(24890, 15)

In [15]:
libros_paises = libros.groupby ('pais')['unidades'].sum().nlargest (10).copy() #Sólo realiza top 9 porque sólo hay 9 países, no 10.
libros_paises

pais
Argentina    5591
Ecuador      5566
Paraguay     5564
Perú         5550
Venezuela    5529
Colombia     5504
Brasil       5473
Uruguay      5377
Chile        5304
Name: unidades, dtype: int64

In [16]:
libros_paises = libros_paises.reset_index ()
libros_paises.columns = ['País', 'Unidades pedidas']
libros_paises['Ranking'] = libros_paises.index + 1
libros_paises

        País  Unidades pedidas  Ranking
0  Argentina              5591        1
1    Ecuador              5566        2
2   Paraguay              5564        3
3       Perú              5550        4
4  Venezuela              5529        5
5   Colombia              5504        6
6     Brasil              5473        7
7    Uruguay              5377        8
8      Chile              5304        9

In [17]:
libros_paises.set_index ('Ranking', inplace= True)
libros_paises

              País  Unidades pedidas
Ranking
1        Argentina              5591
2          Ecuador              5566
3         Paraguay              5564
4             Perú              5550
5        Venezuela              5529
6         Colombia              5504
7           Brasil              5473
8          Uruguay              5377
9            Chile              5304

In [18]:
s_libros = libros_paises.style

s_libros.format ({'Unidades pedidas': '{} prod'})
s_libros

*Seguir con el df original*

---
# **Ejercicio original ventas**

- *Asociar el total de ventas y total de lucros por tipo de producto para apalancar los ingresos por cada tipo de producto vendido*

In [19]:
ganancias_ventas = ventas.groupby (['tipo_producto'])[['ventas', 'ganancia']].sum().sort_values(by= ['ventas'])[::-1] #Sólo ordenará ventas, ya que casi nunca calza lo demás, porque no se puede desagrupar de otra forma
ganancias_ventas.head()

                                 ventas  ganancia
tipo_producto
Neumáticos                   1022428.97  67460.05
Herramientas                  995158.41  41020.34
Macetas                       696044.18  33941.85
Herramientas de jardinería    648879.72  53202.88
Materiales de revestimiento   629656.36 -28869.01

In [20]:
ganancias_ventas.index.name = 'Tipo de producto'
ganancias_ventas.head()

                                 ventas  ganancia
Tipo de producto
Neumáticos                   1022428.97  67460.05
Herramientas                  995158.41  41020.34
Macetas                       696044.18  33941.85
Herramientas de jardinería    648879.72  53202.88
Materiales de revestimiento   629656.36 -28869.01

In [21]:
ganancias_ventas_style = ganancias_ventas.style

In [22]:
ganancias_ventas_style = ganancias_ventas_style.format ('USD {:,.2f}'). \
                                                highlight_max (color= 'lightgreen'). \
                                                highlight_min (color= 'red') #highlight es resaltar

ganancias_ventas_style

In [23]:
ganancias_ventas_style.background_gradient (cmap= 'Blues') #Existe Greens, etc...

## *Pedidos por region*

In [24]:
pedidos_region = ventas['region'].value_counts().to_frame()
pedidos_region

              count
region
Buenos Aires   2822
Litoral        1924
Norte          1555
Central        1276
Cuyo            915
Patagónica      448

In [25]:
pedidos_region.index.name = 'Región'
pedidos_region.rename (columns= {'count': 'N° pedidos'}, inplace= True)
porcentaje = pedidos_region['N° pedidos'].to_numpy()
porcentaje = porcentaje*100 / np.sum(porcentaje)
porcentaje

array([31.56599553, 21.5212528 , 17.39373602, 14.27293065, 10.23489933,
        5.01118568])

In [26]:
pedidos_region ['Ponderación de pedidos'] = porcentaje
estilo_region = pedidos_region.style

In [27]:
estilo_region

In [28]:
estilo_region.format ({'Ponderación de pedidos': '{:.2f} %'}) \
                    .bar(subset= 'Ponderación de pedidos', vmin= 0, vmax= 100, cmap='Reds')

# se puede utilizar color = '#COLOR' en vez de cmap...

# 'Greens' - verde claro a oscuro
# 'Blues' - azul claro a oscuro
# 'Reds' - rojo claro a oscuro
# 'Oranges' - naranja claro a oscuro
# 'YlGn' - amarillo a verde
# 'GnBu' - verde a azul
# 'PuBu' - púrpura a azul

## *Formatos DataTime*

In [30]:
meses = ventas.copy()

In [31]:
meses = meses.sort_values ('fecha_pedido')
meses ['mes'] = meses ['fecha_pedido'].dt.strftime ('%Y - %B') # El simbolo %B significa MES en MAYÚSCULAS
meses.reset_index (drop= True, inplace= True)
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia,mes
0,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44,2016 - January
1,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32,2016 - January
2,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13,2016 - January
3,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26,2016 - January
4,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31,2016 - January
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63,2019 - December
8936,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69,2019 - December
8937,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60,2019 - December
8938,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68,2019 - December
8939,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00,2019 - December

### *Tabla dinámica de resumen*

- *Pivot Table lo que hace es hacer un resumen con estadísticas básicas en una tabla (como sumas, restas, divisiones, promedios, etc)*
- *Pivot en su defecto, toma todos los datos y los separa con los parámetros que uno desee, pudiendo agruparlos de forma más eficiente o separarlos en distintas categorías*

In [32]:
ventas_mensuales = meses.pivot_table (index= meses.departamento, columns= 'mes', values= 'cantidad', aggfunc= 'sum', sort= False) # False por defecto
ventas_mensuales

mes,2016 - January,2016 - February,2016 - March,2016 - April,2016 - May,2016 - June,2016 - July,2016 - August,2016 - September,2016 - October,...,2019 - March,2019 - April,2019 - May,2019 - June,2019 - July,2019 - August,2019 - September,2019 - October,2019 - November,2019 - December
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,...,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,...,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,...,107,131,172,151,162,132,282,213,312,395

In [ ]:
pd.set_option ('display.max_columns', None) # Para ver todas las columnas
ventas_mensuales.head()
# Volver a resumir las columnas por default: pd.reset_option('display.max_columns')

mes,2016 - January,2016 - February,2016 - March,2016 - April,2016 - May,2016 - June,2016 - July,2016 - August,2016 - September,2016 - October,2016 - November,2016 - December,2017 - January,2017 - February,2017 - March,2017 - April,2017 - May,2017 - June,2017 - July,2017 - August,2017 - September,2017 - October,2017 - November,2017 - December,2018 - January,2018 - February,2018 - March,2018 - April,2018 - May,2018 - June,2018 - July,2018 - August,2018 - September,2018 - October,2018 - November,2018 - December,2019 - January,2019 - February,2019 - March,2019 - April,2019 - May,2019 - June,2019 - July,2019 - August,2019 - September,2019 - October,2019 - November,2019 - December
departamento,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,716,525,97,131,278,271,269,321,268,322,663,260,746,628,190,177,260,338,463,473,413,380,757,402,727,770,361,205,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,236,154,55,44,74,111,94,59,88,117,180,100,179,235,59,49,112,72,124,118,117,123,181,103,253,189,109,63,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,213,269,93,38,100,85,76,120,128,106,194,129,259,258,91,67,127,128,171,117,132,113,227,171,308,294,83,67,107,131,172,151,162,132,282,213,312,395

In [37]:
estilo_mensual = ventas_mensuales.style
estilo_mensual.set_sticky (axis = 'index') # Para fijar los índices

### *Fijar encabezado*

- estilo_app.set_sticky(axis=1)
- estilo_app.set_sticky(axis='columns')

# **Ejercicio**

- *El desafío ahora es proporcionar una visualización que permita mostrar el tiempo medio de entrega de pedidos durante los meses de los años 2013 a 2015 por cada país. Esto permitirá analizar el rendimiento del departamento de transporte de la empresa durante esos años y trazar un plan de mejoras.*