# **Importar bibliotecas**

In [2]:
import pandas as pd
import json

In [3]:
df = pd.read_json ('datos/datos_hosting.json')
display (df.sample(5))

                                       info_inmuebles
21  {'evaluacion_general': '6.0', 'experiencia_loc...
52  {'evaluacion_general': '9.0', 'experiencia_loc...
56  {'evaluacion_general': '9.0', 'experiencia_loc...
16  {'evaluacion_general': '4.0', 'experiencia_loc...
19  {'evaluacion_general': '6.0', 'experiencia_loc...

# **Objetivo**

---
*El objetivo para esta DB es generar un algoritmo capaz de determinar un precio inteligente en base a características de una propiedad, de esta forma sugerir al anfitrión un precio a cobrar asegurando rentabilidades atractivas en momentos de alta demanda*

In [4]:
data = pd.json_normalize (df['info_inmuebles'])
display (data.sample(5))

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
52,9.0,--,4,"[Beautiful apartment in an extremely safe, qui...","[Queen Anne is a wonderful, truly functional v...","[1, 3, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, ...","[1, 3, 2, 1, 2, 1, 2, 2, 2, 1, 3, 1, 1, 2, 1, ...","[1, 2, 2, 2, 2, 3, 2, 2, 2, 1, 2, 2, 1, 2, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$100.00, $200.00, $250.00, $100.00, $500.00, ...","[$40.00, $80.00, $99.00, $40.00, $100.00, $75....","[$150.00, $175.00, $159.00, $110.00, $350.00, ..."
58,nan,--,1,"[By Special Request Only, This clean bedroom h...","[--, --, --, --, This area is right on the str...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Pull-out Sofa, Real Bed, Real Bed, Real Bed, ...","[{TV,Internet,""Wireless Internet"",Kitchen,Esse...","[$0, $500.00, $0, $0, $0, $350.00, $350.00, $3...","[$0, $10.00, $0, $0, $15.00, $35.00, $35.00, $...","[$25.00, $50.00, $50.00, $75.00, $40.00, $40.0..."
36,8.0,--,12,[Charming Old World Seattle Craftsman Home wit...,[--],[2],[4],[5],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",K...",[$500.00],[$200.00],[$435.00]
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
34,8.0,--,1,"[Built, run and supported by Seattle tech and ...",[Wallingford is a mostly-residential neighborh...,"[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Indoor...","[$350.00, $350.00, $350.00, $0, $350.00, $0, $...","[$35.00, $35.00, $35.00, $0, $35.00, $10.00, $...","[$40.00, $40.00, $40.00, $35.00, $50.00, $45.0..."

# **Datos**

---
- **evaluacion_general:** se refiere a la puntuación media otorgada para evaluar el alojamiento en la propiedad.
- **experiencia_local:** describe las experiencias ofrecidas durante su estancia en la propiedad.
- **max_hospedes:** informa el número máximo de invitados que permite la ubicación.
- **descripcion_local:** describe la propiedad.
- **descripcion_vecindad:** describe el vecindario alrededor de la propiedad.
- **cantidad_baños:** informa el número de baños disponibles.
- **cantidad_cuartos:** informa el número de habitaciones disponibles.
- **cantidad_camas:** informa el número de camas disponibles.
- **modelo_cama:** informa el modelo de cama ofrecido.
- **comodidades:** informa las comodidades que ofrece la propiedad.
- **cuota_deposito:** informa la tarifa mínima de depósito para la seguridad del hosting.
- **cuota_limpieza:** informa el cargo cobrado por el servicio de limpieza.
- **precio:** se refiere al precio base a cobrar por la estancia diaria en la propiedad.

## *Limpieza de la DB*

---
*A partir de la cuarta columna [3], los elementos del DataFrame contienen listas de más elementos que debieran estar en distintas **filas** por lo que se utiliza el método explode() para descomponer estos conjuntos de datos*

In [5]:
columnas = list(data.columns)
columnas

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_baños',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

In [6]:
data = data.explode (columnas[3:])
display(data)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [7]:
data.reset_index(inplace=True, drop=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [8]:
import numpy as np

In [9]:
col_numeric = ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas', 'max_hospedes']
data[col_numeric] = data [col_numeric].astype(np.int64)

data['evaluacion_general'] = data ['evaluacion_general'].astype(np.float64)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

## *Símbolos extraños*

In [10]:
data['precio'] = data['precio'].apply(lambda x: x.replace ('$', '').replace (',', '').strip())
data['precio'] = data ['precio'].astype(np.float64)
display(data)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,NaN,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,299.0
3814,NaN,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,199.0
3815,NaN,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,400.0
3816,NaN,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,250.0
3817,NaN,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,350.0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

***¡Importante!***

- *Cuando se trabaja con series (una columna) se puede utilizar la función "apply", si es dos o más columnas ya es un DataFrame y se debe trabajar con "applymap" o mejor con la función "map" que es igual a applymap, ya que esta última mencionada está obsoleta*

In [12]:
data [['cuota_deposito', 'cuota_limpieza']] = data [['cuota_deposito', 'cuota_limpieza']].map(lambda x: x.replace ('$' , '').replace (',', '').strip())

In [13]:
data [['cuota_deposito', 'cuota_limpieza']] = data [['cuota_deposito', 'cuota_limpieza']].astype (np.float64)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   float64
 11  cuota_limpieza        3818 non-null   float64
 12  precio                3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

# **Tokenización**

---
- *En la tokenización lo que se busca es tomar elementos strings de una serie (comentarios, opiniones, descripción de un producto, etc) y buscar keywords para asignar una ponderación de importancia u otro factor relevante a esta para que explique a una variable dependiente*

## *Limpieza de serie*

- *Para este ejercicio se utilizará la serie "descripcion_local" para limpiarla y confeccionar posteriormente el algoritmo*

In [14]:
data['descripcion_local'] = data['descripcion_local'].str.lower()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   float64
 11  cuota_limpieza        3818 non-null   float64
 12  precio                3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

*Para eliminar símbolos extraños se utiliza: **[^a-zA-Z0-9\-\']** y **(?<!\w)-(?!\w)***

- "^" sirve para negación en un reemplazo, es decir: no reemplazar lo siguiente, pero sí todo lo demás
- a-z, A-Z para referirse a cualquier letra/palabra y 0-9 para cualquier número
- \- y \' para que no reemplace las comillas simples ni el guión
---
- Podría existir una palabra como "two - bedroom" y la idea es tokenizar la frase completa, no separar todo, eso se hace con (?<!\w)-(?!\w)

In [15]:
data['descripcion_local'] = data['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ', regex=True)
data['descripcion_local'] = data['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ', regex=True)

## *Tokenizar*

In [16]:
data['descripcion_local'] = data['descripcion_local'].str.split()
display (data.descripcion_local)

0       [this, clean, and, comfortable, one, bedroom, ...
1       [our, century, old, upper, queen, anne, house,...
2       [cozy, room, in, two-bedroom, apartment, along...
3       [very, lovely, and, cozy, room, for, one, conv...
4       [the, studio, at, mibbett, hollow', is, in, a,...
                              ...
3813    [beautiful, craftsman, home, in, the, historic...
3814    [located, in, a, very, easily, accessible, are...
3815    [this, home, is, fully, furnished, and, availa...
3816    [this, business-themed, modern, home, features...
3817    [this, welcoming, home, is, in, the, quiet, re...
Name: descripcion_local, Length: 3818, dtype: object

In [17]:
data['comodidades'] = data['comodidades'].str.replace('[{}"]', '', regex = True)

In [18]:
data['comodidades'] = data['comodidades'].str.split(',')

In [19]:
data['comodidades'].iloc[3]

['Internet',
 'Wireless Internet',
 'Kitchen',
 'Free Parking on Premises',
 'Breakfast',
 'Heating',
 'Family/Kid Friendly',
 'Washer',
 'Dryer',
 'Smoke Detector',
 'First Aid Kit',
 'Fire Extinguisher',
 'Essentials',
 'Shampoo',
 'Lock on Bedroom Door']

# **Datetime**

In [20]:
import datetime

**Para fecha y hora actual:**
- *datetime.datetime.now()*

**Para fecha actual:**
- *datetime.date.today()*

In [21]:

# creando dos objetos date con fechas diferentes
data_1 = datetime.date(2022, 1, 1)
data_2 = datetime.date(2023, 1, 1)

# calculando la diferencia entre las dos fechas
diferencia = data_2 - data_1

print("Diferencia entre las dos fechas:", diferencia)

Diferencia entre las dos fechas: 365 days, 0:00:00

## *Importar DB*

In [22]:
data_dt = pd.read_json ('datos/inmuebles_disponibles.json')
data_dt.shape

(365000, 4)

In [23]:
data_dt['fecha'] = pd.to_datetime (data_dt['fecha'])

In [24]:
data_dt['fecha'].dt.strftime ('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: fecha, Length: 365000, dtype: object

### *Habitaciones disponibles cada mes*

In [25]:
data_dt.groupby (data_dt['fecha'].dt.strftime ('%Y-%m'))[['lugar_disponible']].sum().sort_values('fecha')[::-1]

         lugar_disponible
fecha
2017-01              1574
2016-12             24409
2016-11             23352
2016-10             23765
2016-09             22471
2016-08             22529
2016-07             22329
2016-06             23651
2016-05             23842
2016-04             22597
2016-03             23357
2016-02             20128
2016-01             16543

In [26]:
data_dt['precio'] = data_dt['precio'].str.replace ('[^0-9]', '', regex= True)

In [27]:
data_dt['precio'] = data_dt['precio'].astype (np.float64)

In [28]:
data_dt['precio'].interpolate (method= 'linear', inplace= True)
data_dt['precio'] = data_dt['precio'].round(2)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_15832\536035175.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_dt['precio'].interpolate (method= 'linear', inplace= True)

In [29]:
data_dt = data_dt.dropna().drop_duplicates()

In [30]:
data_dt.shape

(364944, 4)

In [31]:
data_dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364944 entries, 56 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                364944 non-null  int64
 1   fecha             364944 non-null  datetime64[ns]
 2   lugar_disponible  364944 non-null  bool
 3   precio            364944 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB